// Generated by CoffeeScript 1.7.1
(function() {
  var config, dbHelper;

  config = require("../../config.json");

  dbHelper = require("mysql-dbhelper")({
    dbConfig: config.dbConfig
  });

  exports.createConnection = dbHelper.createConnection;

}).call(this);

//# sourceMappingURL=dbHelper.map
