// Generated by CoffeeScript 1.7.1
(function() {
  var dbHelper, _;

  dbHelper = require("./dbHelper");

  _ = require('underscore');

  exports["new"] = function(snippet, cb) {
    var conn, sql, tag, tagNameArr, _i, _len, _ref;
    sql = "insert into snippet_revision(\n	snippetId,\n	version,\n	title,\n	content,\n	tags,\n	addTime,\n	state\n)\nvalues(\n	?,?,?,?,?,now(),0\n)";
    conn = dbHelper.createConnection();
    conn.connect();
    tagNameArr = [];
    _ref = snippet.tags;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tag = _ref[_i];
      tagNameArr.push(tag.name);
    }
    return conn.insert(sql, [snippet.id, snippet.version, snippet.title, snippet.content, tagNameArr.join('|')], function() {
      conn.end();
      return cb.apply(this, arguments);
    });
  };

}).call(this);

//# sourceMappingURL=dbSnippetRevision.map
