// Generated by CoffeeScript 1.7.1
(function() {
  exports["new"] = function(conn, tag, cb) {
    var sql;
    sql = "select id from tag where name=? limit 1";
    return conn.executeScalar(sql, [tag], function(err, tagId) {
      if (err) {
        return cb(err);
      } else {
        if (!tagId) {
          sql = "insert into tag(name,addTime) values(?,now())";
          return conn.insert(sql, [tag], function(err, success, tagId) {
            if (err) {
              return cb(err);
            } else if (!success) {
              return cb(new Error("fail to add tag " + tag));
            } else {
              return cb(null, tagId);
            }
          });
        } else {
          return cb(null, tagId);
        }
      }
    });
  };

}).call(this);

//# sourceMappingURL=dbTag.map
