// Generated by CoffeeScript 1.7.1
(function() {
  var dbHelper, _;

  dbHelper = require("./dbHelper");

  _ = require('underscore');


  /*
      认证
   */

  exports.auth = function(email, password, cb) {
    var conn, sql;
    sql = "select id\nfrom user\nwhere email=?\nand password=?\nand state =0;";
    conn = dbHelper.createConnection();
    conn.connect();
    return conn.executeFirstRow(sql, [email, password], function(err, row) {
      conn.end();
      if (err) {
        return cb(err);
      } else if (row) {
        return cb(null);
      } else {
        return cb(new Error("fail"));
      }
    });
  };

}).call(this);

//# sourceMappingURL=dbUser.map
