// Generated by CoffeeScript 1.7.1
(function() {
  var datePart, timePart, _;

  _ = require("underscore");


  /*
      pretty print date
   */

  exports.prettyDate = function(date) {
    if (_.isString(date)) {
      date = new Date(date);
    }
    return datePart(date);
  };


  /*
      pretty print datetime
   */

  exports.prettyDateTime = function(date) {
    if (_.isString(date)) {
      date = new Date(date);
    }
    return "" + (datePart(date)) + " " + (timePart(date));
  };

  datePart = function(date) {
    var d, m, monthNames, y;
    d = date.getDate();
    monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    m = monthNames[date.getMonth()];
    y = date.getFullYear();
    return "" + d + " " + m + " " + y;
  };

  timePart = function(date) {
    var h, m;
    h = date.getHours();
    m = date.getMinutes();
    return "" + h + ":" + m;
  };


  /*
      page state
   */

  exports.pageState = {
    inProgress: 0,
    archive: 1,
    "delete": 4
  };

}).call(this);

//# sourceMappingURL=dataHelper.map
