// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, config, express, http, path;

  express = require("express");

  http = require("http");

  path = require("path");

  config = require("./config.json");

  app = express();

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express.cookieParser('sibo.me'));

  require("simple-mvc")({
    controllerPath: "api"
  }, app);

  app.use(function(req, res) {
    return res.send("404:not found!");
  });

  app.use(function(err, req, res) {
    return res.send("500:server error!");
  });

  process.on("uncaughtException", function(err) {
    return console.dir(err);
  });

  http.createServer(app).listen(config.port.api, function() {
    return console.log("api.sibo.me listening on port " + config.port.api);
  });

}).call(this);

//# sourceMappingURL=api.map
