// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, config, express, http, path, _;

  express = require("express");

  http = require("http");

  path = require("path");

  config = require("./config.json");

  app = express();

  _ = require("underscore");

  app.use(express.favicon(__dirname + "/public/favicon.ico"));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "public")));

  app.use(express.cookieParser('sibo.me'));

  require("multi-process-session")(app);

  app.use(function(req, res, next) {
    res.err = function(err) {
      return res.send({
        code: 1,
        message: err.message
      });
    };
    res.data = function(data) {
      if (_.isUndefined(data.code)) {
        data.code = 0;
      }
      if (_.isUndefined(data.message)) {
        data.message = "ok";
      }
      return res.send(data);
    };
    res.ok = function() {
      return res.send({
        code: 0,
        message: "ok"
      });
    };
    return next();
  });

  require("simple-mvc")({
    defaultEngine: "jade",
    defaultViewEngine: "jade"
  }, app);

  app.use(function(req, res) {
    return res.send("404:not found!");
  });

  app.use(function(err, req, res) {
    return res.send("500:server error!");
  });

  process.on("uncaughtException", function(err) {
    return console.dir(err);
  });

  http.createServer(app).listen(config.port.app, function() {
    return console.log("www.sibo.me listening on port " + config.port.app);
  });

}).call(this);

//# sourceMappingURL=app.map
