// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, config, express, http, path;

  express = require("express");

  http = require("http");

  path = require("path");

  config = require("./config");

  app = express();

  app.use(express.favicon(__dirname + "/public/favicon.ico"));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "public")));

  if (!config.isProduct()) {
    app.use(express.errorHandler());
  }

  app.use(express.cookieParser('sibo.me'));

  require("multi-process-session")(app);

  require("simple-mvc")({
    defaultEngine: "jade",
    defaultViewEngine: "jade"
  }, app);

  http.createServer(app).listen(config.port.app, function() {
    return console.log("Express server listening on port " + config.port.app);
  });

}).call(this);

//# sourceMappingURL=app.map
