// Generated by CoffeeScript 1.7.1
(function() {
  exports.temple = function(req, res) {
    res.write("temple");
    return res.end();
  };


  /*
      three circle
   */

  exports.circle = function(req, res) {
    return res.render("circle");
  };

  exports.parallasScroller = function(req, res) {
    return res.render("parallasScroller");
  };

}).call(this);

//# sourceMappingURL=game.map
