// Generated by CoffeeScript 1.7.1

/*
    home
 */

(function() {
  exports.index = function(req, res) {
    return res.render("index", {
      title: "sibo.me"
    });
  };

}).call(this);

//# sourceMappingURL=home.map
