// Generated by CoffeeScript 1.7.1
(function() {
  var pinBll;

  pinBll = require("../model/bll/pin");

  exports.index = function(req, res) {
    return pinBll.all(function(err, pageData) {
      if (err) {
        return res.send(err.message);
      } else {
        return res.render("index", {
          pageData: pageData
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=pinIt.map
