// Generated by CoffeeScript 1.7.1
(function() {
  var html_readability, request;

  html_readability = require("html-readability");

  request = require("request");

  exports.index = function(req, res) {
    var demoSites;
    demoSites = ["http://weblogs.asp.net/bsimser/day-to-day-with-subversion", "http://jianshu.io/p/77c949565112", "http://sports.sina.com.cn/nba/2014-08-24/03547305054.shtml", "https://medium.com/code-adventures/farewell-node-js-4ba9e7f3e52b"];
    return res.render("index", {
      demoSites: demoSites
    });
  };

  exports.demo = function(req, res) {
    var e, url;
    url = req.query.url;
    if (url) {
      try {
        url = decodeURIComponent(url);
        return request(url, function(err, response, body) {
          var article, readability;
          if (err) {
            return res.send(err);
          } else {
            readability = new html_readability({
              url: url,
              content: body.toString()
            });
            article = readability.run();
            return res.render("demo", {
              title: article.title,
              article: article
            });
          }
        });
      } catch (_error) {
        e = _error;
        return res.send(e);
      }
    } else {
      return res.send("must have a url");
    }
  };

}).call(this);

//# sourceMappingURL=readability.map
