// Generated by CoffeeScript 1.7.1
(function() {
  var userBll;

  userBll = require("../model/bll/user");

  exports.login_GET_POST = function(req, res) {
    var email, password;
    if (req.method === "GET") {
      return res.render("login");
    } else {
      email = req.body.email;
      password = req.body.password;
      return userBll.auth(email, password, function(err) {
        if (err) {
          res.write(err.message);
          return res.end();
        } else {
          res.session.auth = true;
          return res.redirect("/snippets");
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=user.map
