// Generated by CoffeeScript 1.7.1
(function() {
  var dbPin;

  dbPin = require('../dal/dbPin');


  /*
      create a new pin
   */

  exports["new"] = function(data, cb) {
    return dbPin["new"](data, cb);
  };


  /*
      get pin count on a page
   */

  exports.countOnPage = function(url, cb) {
    return dbPin.countOnPage(url, cb);
  };


  /*
      get all pin on a page
   */

  exports.pinOnPage = function(url, cb) {
    return dbPin.pinOnPage(url, cb);
  };


  /*
      get all pin by state
   */

  exports.all = function(state, cb) {
    return dbPin.all(state, cb);
  };


  /*
      update a page info
   */

  exports.updatePage = function(info, cb) {
    return dbPin.updatePage(info, cb);
  };


  /*
      archive page
   */

  exports.archive = function(id, cb) {
    return dbPin.archive(id, cb);
  };

  exports.search = function(key, cb) {
    if (key) {
      return dbPin.search(key, cb);
    } else {
      return cb(new Error("key word can't be empty"));
    }
  };

}).call(this);
