// Generated by CoffeeScript 1.7.1
(function() {
  var dbPin;

  dbPin = require('../dal/dbPin');

  exports["new"] = function(data, cb) {
    return dbPin["new"](data, cb);
  };

  exports.countOnPage = function(url, cb) {
    return dbPin.countOnPage(url, cb);
  };

  exports.pinOnPage = function(url, cb) {
    return dbPin.pinOnPage(url, cb);
  };

  exports.all = function(cb) {
    return dbPin.all(cb);
  };

}).call(this);

//# sourceMappingURL=pin.map
