// Generated by CoffeeScript 1.7.1
(function() {
  var dbSnippet, marked;

  dbSnippet = require('../dal/dbSnippet');

  marked = require("marked");


  /*
      新建
   */

  exports["new"] = function(snippet, cb) {
    if (snippet.title && snippet.content && snippet.tags) {
      if (snippet.title.indexOf('.md') > 0) {
        snippet.html = marked(snippet.content);
      } else {
        snippet.html = "";
      }
      snippet.tags = snippet.tags.split('|');
      return dbSnippet["new"](snippet, cb);
    }
  };


  /*
      更新
   */

  exports.update = function(snippet, cb) {
    if (snippet.title.toLowerCase().indexOf('.md') > 0) {
      snippet.html = marked(snippet.content);
    } else {
      snippet.html = "";
    }
    snippet.tags = snippet.tags.split('|');
    return dbSnippet.update(snippet, cb);
  };


  /*
      单条
   */

  exports.single = function(id, cb) {
    if (id > 0) {
      return dbSnippet.single(id, cb);
    } else {
      return cb(new Error("invalid request"));
    }
  };


  /*
      delete
   */

  exports["delete"] = function(id, cb) {
    if (id > 0) {
      return dbSnippet["delete"](id, cb);
    } else {
      return cb(new Error("invalid request"));
    }
  };


  /*
      列表
   */

  exports.list = function(cb) {
    return dbSnippet.list(cb);
  };

}).call(this);
