// Generated by CoffeeScript 1.7.1
(function() {
  var dbUser;

  dbUser = require('../dal/dbUser');


  /*
      认证
   */

  exports.auth = function(email, password, cb) {
    if (email && password) {
      return dbUser.auth(email, password, cb);
    } else {
      return cb(new Error("invalid request"));
    }
  };

}).call(this);
